name: mlfromscratch
channels:
  - conda-forge
dependencies:
  - python=3.8.12
  - pip
  - pip:
    - ipynb==0.5.1
    - matplotlib==3.5.0
    - numpy==1.21.4
    - pandas==1.3.4
    - pyvizml==1.0.2
    - requests==2.26.0
    - scikit-learn==1.0.1